import { Container } from 'inversify';
import { TYPES } from './ioc.types';

import IUnitOfService from '../services/interfaces/iunitof.service';
import IUnitOfWork from '../repository/interfaces/iunitofwork.repository';

import UnitOfService from '../services/unitOfService';
import UnitOfWork from '../repository/unitofwork.repository';
import { DateTimeService } from '../services/dateTime.service';

import { AccountController } from '../controllers/auth.controller';
import { UserController } from '../controllers/user.controller';
import { HealthController } from '../controllers/health.controller';
import { CategoryController } from '../controllers/category.controller';
import { ProductController } from '../controllers/product.controller';
import { AttributeController } from '../controllers/attribute.controller';
import { StaffAttendanceController } from '../controllers/staff-attendance.controller';
import { OrderController } from '../controllers/order.controller';
import { OrderItemController } from '../controllers/order-item.controller';
import { PaymentController } from '../controllers/payment.controller';
import { StaffSalaryController } from '../controllers/staff-salary.controller';
import { DashboardController } from '../controllers/dashboard.controller';
import { BrandNameController } from '../controllers/brand-name.controller';
import { StaffController } from '../controllers/staff.controller';
import { StoreController } from '../controllers/store.controller';

import { IAccountService } from '../services/interfaces/Iaccount.service';
import { IUserService } from '../services/interfaces/Iuser.service';
import { IDateTimeService } from '../services/interfaces/idatetime.service';
import { ICategoryService } from '../services/interfaces/Icategory.service';
import { IProductService } from '../services/interfaces/Iproduct.service';
import { IAttributeService } from '../services/interfaces/Iattribute.service';
import { IStaffAttendanceService } from '../services/interfaces/Istaff-attendance.service';
import { IOrderService } from '../services/interfaces/Iorder.service';
import { IOrderItemService } from '../services/interfaces/Iorder-item.service';
import { IPaymentService } from '../services/interfaces/Ipayment.service';
import { IStaffSalaryService } from '../services/interfaces/Istaff-salary.service';
import { IDashboardService } from '../services/interfaces/Idashboard.service';
import { IBrandNameService } from '../services/interfaces/Ibrand-name.service';
import { IStaffService } from '../services/interfaces/Istaff.service';
import { IStoreService } from '../services/interfaces/Istore.service';

import AccountService from '../services/account.service';
import { UserService } from '../services/user.service';
import { CategoryService } from '../services/category.service';
import { ProductService } from '../services/product.service';
import { AttributeService } from '../services/attribute.service';
import { StaffAttendanceService } from '../services/staff-attendance.service';
import { OrderService } from '../services/order.service';
import { OrderItemService } from '../services/order-item.service';
import { PaymentService } from '../services/payment.service';
import { StaffSalaryService } from '../services/staff-salary.service';
import { DashboardService } from '../services/dashboard.service';
import { BrandNameService } from '../services/brand-name.service';
import { StaffService } from '../services/staff.service';
import { StoreService } from '../services/store.service';

import { AccountRepository } from '../repository/account.repository';
import { UserRepository } from '../repository/user.repository';
import { CategoryRepository } from '../repository/category.repository';
import { ProductRepository } from '../repository/product.repository';
import { AttributeRepository } from '../repository/attribute.repository';
import { StaffAttendanceRepository } from '../repository/staff-attendance.repository';
import { OrderRepository } from '../repository/order.repository';
import { OrderItemRepository } from '../repository/order-item.repository';
import { PaymentRepository } from '../repository/payment.repository';
import { StaffSalaryRepository } from '../repository/staff-salary.repository';
import { DashboardRepository } from '../repository/dashboard.repository';
import { BrandNameRepository } from '../repository/brand-name.repository';
import { StaffRepository } from '../repository/staff.repository';
import { StoreRepository } from '../repository/store.repository';

import { IAccountRepository } from '../repository/interfaces/iaccount.repository';
import { IUserRepository } from '../repository/interfaces/iuser.repository';
import { ICategoryRepository } from '../repository/interfaces/icategory.repository';
import { IProductRepository } from '../repository/interfaces/iproduct.repository';
import { IAttributeRepository } from '../repository/interfaces/iattribute.repository';
import { IStaffAttendanceRepository } from '../repository/interfaces/istaff-attendance.repository';
import { IOrderRepository } from '../repository/interfaces/iorder.repository';
import { IOrderItemRepository } from '../repository/interfaces/iorder-item.repository';
import { IPaymentRepository } from '../repository/interfaces/ipayment.repository';
import { IStaffSalaryRepository } from '../repository/interfaces/istaff-salary.repository';
import { IDashboardRepository } from '../repository/interfaces/idashboard.repository';
import { IBrandNameRepository } from '../repository/interfaces/ibrand-name.repository';
import { IStaffRepository } from '../repository/interfaces/istaff.repository';
import { IStoreRepository } from '../repository/interfaces/istore.repository';
import { PurchaseController } from '../controllers/purchase.controller';
import { IPurchaseService } from '../services/interfaces/ipurchase.service';
import { PurchaseService } from '../services/purchase.service';
import { IPurchaseRepository } from '../repository/interfaces/ipurchase.repository';
import { PurchaseRepository } from '../repository/purchase.repository';

export const container = new Container();

container.bind<HealthController>(TYPES.HealthController).to(HealthController);
container.bind<AccountController>(TYPES.AccountController).to(AccountController);
container.bind<UserController>(TYPES.UserController).to(UserController);
container.bind<CategoryController>(TYPES.CategoryController).to(CategoryController);
container.bind<ProductController>(TYPES.ProductController).to(ProductController);
container.bind<AttributeController>(TYPES.AttributeController).to(AttributeController);
container.bind<StaffAttendanceController>(TYPES.StaffAttendanceController).to(StaffAttendanceController);
container.bind<OrderController>(TYPES.OrderController).to(OrderController);
container.bind<OrderItemController>(TYPES.OrderItemController).to(OrderItemController);
container.bind<PaymentController>(TYPES.PaymentController).to(PaymentController);
container.bind<StaffSalaryController>(TYPES.StaffSalaryController).to(StaffSalaryController);
container.bind<DashboardController>(TYPES.DashboardController).to(DashboardController);
container.bind<BrandNameController>(TYPES.BrandNameController).to(BrandNameController);
container.bind<StaffController>(TYPES.StaffController).to(StaffController);
container.bind<StoreController>(TYPES.StoreController).to(StoreController);
container.bind<PurchaseController>(TYPES.PurchaseController).to(PurchaseController);

container.bind<IAccountService>(TYPES.IAccountService).to(AccountService);
container.bind<IUserService>(TYPES.IUserService).to(UserService);
container.bind<ICategoryService>(TYPES.ICategoryService).to(CategoryService);
container.bind<IProductService>(TYPES.IProductService).to(ProductService);
container.bind<IAttributeService>(TYPES.IAttributeService).to(AttributeService);
container.bind<IStaffAttendanceService>(TYPES.IStaffAttendanceService).to(StaffAttendanceService);
container.bind<IOrderService>(TYPES.IOrderService).to(OrderService);
container.bind<IOrderItemService>(TYPES.IOrderItemService).to(OrderItemService);
container.bind<IPaymentService>(TYPES.IPaymentService).to(PaymentService);
container.bind<IStaffSalaryService>(TYPES.IStaffSalaryService).to(StaffSalaryService);
container.bind<IDashboardService>(TYPES.IDashboardService).to(DashboardService);
container.bind<IBrandNameService>(TYPES.IBrandNameService).to(BrandNameService);
container.bind<IStaffService>(TYPES.IStaffService).to(StaffService);
container.bind<IStoreService>(TYPES.IStoreService).to(StoreService);
container.bind<IPurchaseService>(TYPES.IPurchaseService).to(PurchaseService);

container.bind<IAccountRepository>(TYPES.IAccountRepository).to(AccountRepository);
container.bind<IUserRepository>(TYPES.IUserRepository).to(UserRepository);
container.bind<ICategoryRepository>(TYPES.ICategoryRepository).to(CategoryRepository);
container.bind<IProductRepository>(TYPES.IProductRepository).to(ProductRepository);
container.bind<IAttributeRepository>(TYPES.IAttributeRepository).to(AttributeRepository);
container.bind<IStaffAttendanceRepository>(TYPES.IStaffAttendanceRepository).to(StaffAttendanceRepository);
container.bind<IOrderRepository>(TYPES.IOrderRepository).to(OrderRepository);
container.bind<IOrderItemRepository>(TYPES.IOrderItemRepository).to(OrderItemRepository);
container.bind<IPaymentRepository>(TYPES.IPaymentRepository).to(PaymentRepository);
container.bind<IStaffSalaryRepository>(TYPES.IStaffSalaryRepository).to(StaffSalaryRepository);
container.bind<IDashboardRepository>(TYPES.IDashboardRepository).to(DashboardRepository);
container.bind<IBrandNameRepository>(TYPES.IBrandNameRepository).to(BrandNameRepository);
container.bind<IStaffRepository>(TYPES.IStaffRepository).to(StaffRepository);
container.bind<IStoreRepository>(TYPES.IStoreRepository).to(StoreRepository);
container.bind<IPurchaseRepository>(TYPES.IPurchaseRepository).to(PurchaseRepository);

container.bind<IUnitOfService>(TYPES.IUnitOfService).to(UnitOfService);
container.bind<IUnitOfWork>(TYPES.IUnitOfWork).to(UnitOfWork);
container.bind<IDateTimeService>(TYPES.IDateTimeService).to(DateTimeService).inSingletonScope();
