export const TYPES = {
  IUnitOfService: Symbol.for("UnitOfService"),
  IDateTimeService: Symbol.for("IDateTimeService"),
  IAccountService: Symbol.for("AccountService"),
  IUserService: Symbol.for("UserService"),
  ICategoryService: Symbol.for("CategoryService"),
  IProductService: Symbol.for("ProductService"),
  IProductVariantService: Symbol.for("ProductVariantService"),
  IAttributeService: Symbol.for("AttributeService"),
  IProductAttributeService: Symbol.for("ProductAttributeService"),
  IStaffAttendanceService: Symbol.for("StaffAttendanceService"),
  IOrderService: Symbol.for("OrderService"),
  IOrderItemService: Symbol.for("OrderItemService"),
  IPaymentService: Symbol.for("PaymentService"),
  IStaffSalaryService: Symbol.for("StaffSalaryService"),
  IDashboardService: Symbol.for("DashboardService"),
  IBrandNameService: Symbol.for("BrandNameService"),
  IStaffService: Symbol.for("StaffService"),

  //Controllers
  HealthController: Symbol.for("HealthController"),
  AccountController: Symbol.for("AccountController"),
  UserController: Symbol.for("UserController"),
  CategoryController: Symbol.for("CategoryController"),
  ProductController: Symbol.for("ProductController"),
  ProductVariantController: Symbol.for("ProductVariantController"),
  AttributeController: Symbol.for("AttributeController"),
  ProductAttributeController: Symbol.for("ProductAttributeController"),
  StaffAttendanceController: Symbol.for("StaffAttendanceController"),
  OrderController: Symbol.for("OrderController"),
  OrderItemController: Symbol.for("OrderItemController"),
  PaymentController: Symbol.for("PaymentController"),
  StaffSalaryController: Symbol.for("StaffSalaryController"),
  DashboardController: Symbol.for("DashboardController"),
  BrandNameController: Symbol.for("BrandNameController"),
  StaffController: Symbol.for("StaffController"),

  //Repositories
  IUnitOfWork: Symbol.for("UnitOfWork"),
  IAccountRepository: Symbol.for("AccountRepository"),
  IUserRepository: Symbol.for("UserRepository"),
  ICategoryRepository: Symbol.for("CategoryRepository"),
  IProductRepository: Symbol.for("ProductRepository"),
  IProductVariantRepository: Symbol.for("ProductVariantRepository"),
  IAttributeRepository: Symbol.for("AttributeRepository"),
  IProductAttributeRepository: Symbol.for("ProductAttributeRepository"),
  IStaffAttendanceRepository: Symbol.for("StaffAttendanceRepository"),
  IOrderRepository: Symbol.for("OrderRepository"),
  IOrderItemRepository: Symbol.for("OrderItemRepository"),
  IPaymentRepository: Symbol.for("PaymentRepository"),
  IStaffSalaryRepository: Symbol.for("StaffSalaryRepository"),
  IDashboardRepository: Symbol.for("DashboardRepository"),
  IBrandNameRepository: Symbol.for("BrandNameRepository"),
  IStaffRepository: Symbol.for("StaffRepository"),
};
