import path from 'path';

const port = process.env.PORT || 4000;

// Determine the server URL used in Swagger UI. When deployed on Vercel,
// VERCEL_URL is set to <project>.vercel.app. Prefer an explicit PUBLIC_URL
// if provided (useful for custom domains). Fallback to localhost for dev.
//const publicUrl = 'https://backend-ruddy-tau-76.vercel.app/docs';

export const swaggerOptions = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'TCI API 🏨',
      version: '1.0.0',
      description: 'API documentation for TCI Platform',
    },
    // Use a relative server URL so Swagger UI uses the current origin.
    // This avoids localhost being embedded at build time when deployed to Vercel.
    // servers: [{ url: '/' }],
    components: {
      securitySchemes: {
        bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
      },
      // --- MOVED SCHEMAS INSIDE COMPONENTS ---
      schemas: {
        User: {
          type: 'object',
          properties: {
            id: { type: 'string', example: 'STU-2025-1234' },
            name: { type: 'string', example: 'John Doe' },
            email: { type: 'string', example: 'john@example.com' },
            role: {
              type: 'string',
              enum: ['ADMIN', 'STUDENT'],
              example: 'STUDENT',
            },
          },
        },
        LoginRequest: {
          type: 'object',
          required: ['email', 'password'],
          properties: {
            email: { type: 'string' },
            password: { type: 'string' },
          },
        },
        Product: {
          type: 'object',
          properties: {
            id: { type: 'integer', example: 1 },
            name: { type: 'string', example: 'Wireless Mouse' },
            brandNameId: { type: 'integer', nullable: true, example: 2 },
            slug: { type: 'string', example: 'wireless-mouse' },
            description: { type: 'string', nullable: true, example: 'A high-precision wireless mouse' },
            sku: { type: 'string', example: 'SKU-001' },
            price: { type: 'number', example: 999.99 },
            cost: { type: 'number', nullable: true, example: 500 },
            stock: { type: 'integer', example: 50 },
            lowStockThreshold: { type: 'integer', nullable: true, example: 5 },
            categoryId: { type: 'integer', example: 3 },
            images: { type: 'array', items: { type: 'string' }, example: ['https://example.com/image1.jpg'] },
            storeId: { type: 'integer', nullable: true, example: 1 },
            status: { type: 'string', enum: ['Published', 'Draft', 'Trash'], example: 'Published' },
            displayOrder: { type: 'integer', nullable: true, example: 0 },
            createdById: { type: 'integer', example: 1 },
            updatedById: { type: 'integer', nullable: true, example: 2 },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time', nullable: true },
          },
        },
        CreateProductRequest: {
          type: 'object',
          required: ['name', 'slug', 'sku', 'price', 'categoryId'],
          properties: {
            name: { type: 'string', example: 'Wireless Mouse' },
            brandNameId: { type: 'integer', nullable: true, example: 2 },
            slug: { type: 'string', example: 'wireless-mouse' },
            description: { type: 'string', nullable: true, example: 'A high-precision wireless mouse' },
            sku: { type: 'string', example: 'SKU-001' },
            price: { type: 'number', example: 999.99 },
            cost: { type: 'number', nullable: true, example: 500 },
            stock: { type: 'integer', example: 50 },
            lowStockThreshold: { type: 'integer', nullable: true, example: 5 },
            categoryId: { type: 'integer', example: 3 },
            images: { type: 'array', items: { type: 'string' }, example: ['https://example.com/image1.jpg'] },
            storeId: { type: 'integer', nullable: true, example: 1 },
            status: { type: 'string', enum: ['Published', 'Draft', 'Trash'], example: 'Published' },
            displayOrder: { type: 'integer', nullable: true, example: 0 },
          },
        },
        UpdateProductRequest: {
          type: 'object',
          properties: {
            name: { type: 'string', example: 'Wireless Mouse' },
            brandNameId: { type: 'integer', nullable: true, example: 2 },
            slug: { type: 'string', example: 'wireless-mouse' },
            description: { type: 'string', nullable: true, example: 'A high-precision wireless mouse' },
            sku: { type: 'string', example: 'SKU-001' },
            price: { type: 'number', example: 999.99 },
            cost: { type: 'number', nullable: true, example: 500 },
            stock: { type: 'integer', example: 50 },
            lowStockThreshold: { type: 'integer', nullable: true, example: 5 },
            categoryId: { type: 'integer', example: 3 },
            images: { type: 'array', items: { type: 'string' }, example: ['https://example.com/image1.jpg'] },
            storeId: { type: 'integer', nullable: true, example: 1 },
            status: { type: 'string', enum: ['Published', 'Draft', 'Trash'], example: 'Published' },
            displayOrder: { type: 'integer', nullable: true, example: 0 },
          },
        },
        ProductVariant: {
          type: 'object',
          properties: {
            id: { type: 'integer', example: 1 },
            name: { type: 'string', example: 'Red Large Variant' },
            slug: { type: 'string', nullable: true, example: 'red-large-variant' },
            productId: { type: 'integer', example: 1 },
            brandNameId: { type: 'integer', nullable: true, example: 2 },
            productAttributeId: { type: 'integer', nullable: true, example: 3 },
            attributeId: { type: 'integer', nullable: true, example: 4 },
            cost: { type: 'integer', example: 500 },
            Price: { type: 'integer', example: 1000 },
            stock: { type: 'integer', example: 100 },
            lowStockThreshold: { type: 'integer', nullable: true, example: 5 },
            images: { type: 'array', items: { type: 'string' }, example: ['https://example.com/variant1.jpg'] },
            status: { type: 'string', enum: ['Published', 'Draft', 'Trash'], example: 'Published' },
            displayOrder: { type: 'integer', nullable: true, example: 0 },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time', nullable: true },
            isDefault: { type: 'boolean', example: false },
            extraPrice: { type: 'number', nullable: true, example: 50.00 },
            varient: { type: 'string', nullable: true, example: 'Standard' },
            size: { type: 'string', nullable: true, example: 'Large' },
            material: { type: 'string', nullable: true, example: 'Cotton' },
            voltage: { type: 'string', nullable: true, example: '220V' },
            color: { type: 'string', nullable: true, example: 'Red' },
            extraSku: { type: 'string', nullable: true, example: 'SKU-VAR-001' },
          },
        },
        CreateProductVariantRequest: {
          type: 'object',
          required: ['name', 'productId'],
          properties: {
            name: { type: 'string', example: 'Red Large Variant' },
            slug: { type: 'string', nullable: true, example: 'red-large-variant' },
            productId: { type: 'integer', example: 1 },
            brandNameId: { type: 'integer', nullable: true, example: 2 },
            productAttributeId: { type: 'integer', nullable: true, example: 3 },
            attributeId: { type: 'integer', nullable: true, example: 4 },
            cost: { type: 'integer', example: 500 },
            Price: { type: 'integer', example: 1000 },
            stock: { type: 'integer', example: 100 },
            lowStockThreshold: { type: 'integer', nullable: true, example: 5 },
            images: { type: 'array', items: { type: 'string' }, example: ['https://example.com/variant1.jpg'] },
            status: { type: 'string', enum: ['Published', 'Draft', 'Trash'], example: 'Published' },
            displayOrder: { type: 'integer', nullable: true, example: 0 },
            isDefault: { type: 'boolean', example: false },
            extraPrice: { type: 'number', nullable: true, example: 50.00 },
            varient: { type: 'string', nullable: true, example: 'Standard' },
            size: { type: 'string', nullable: true, example: 'Large' },
            material: { type: 'string', nullable: true, example: 'Cotton' },
            voltage: { type: 'string', nullable: true, example: '220V' },
            color: { type: 'string', nullable: true, example: 'Red' },
            extraSku: { type: 'string', nullable: true, example: 'SKU-VAR-001' },
          },
        },
        UpdateProductVariantRequest: {
          type: 'object',
          properties: {
            name: { type: 'string', example: 'Red Large Variant' },
            slug: { type: 'string', nullable: true, example: 'red-large-variant' },
            brandNameId: { type: 'integer', nullable: true, example: 2 },
            productAttributeId: { type: 'integer', nullable: true, example: 3 },
            attributeId: { type: 'integer', nullable: true, example: 4 },
            cost: { type: 'integer', example: 500 },
            Price: { type: 'integer', example: 1000 },
            stock: { type: 'integer', example: 100 },
            lowStockThreshold: { type: 'integer', nullable: true, example: 5 },
            images: { type: 'array', items: { type: 'string' }, example: ['https://example.com/variant1.jpg'] },
            status: { type: 'string', enum: ['Published', 'Draft', 'Trash'], example: 'Published' },
            displayOrder: { type: 'integer', nullable: true, example: 0 },
            isDefault: { type: 'boolean', example: false },
            extraPrice: { type: 'number', nullable: true, example: 50.00 },
            varient: { type: 'string', nullable: true, example: 'Standard' },
            size: { type: 'string', nullable: true, example: 'Large' },
            material: { type: 'string', nullable: true, example: 'Cotton' },
            voltage: { type: 'string', nullable: true, example: '220V' },
            color: { type: 'string', nullable: true, example: 'Red' },
            extraSku: { type: 'string', nullable: true, example: 'SKU-VAR-001' },
          },
        },
        // ========== STAFF ATTENDANCE ==========
        StaffAttendance: {
          type: 'object',
          properties: {
            id: { type: 'integer', example: 1 },
            staffId: { type: 'integer', example: 5 },
            date: { type: 'string', format: 'date-time', example: '2026-05-22T00:00:00Z' },
            status: { type: 'string', enum: ['PRESENT', 'ABSENT', 'LATE', 'LEAVE', 'HALF_DAY'], example: 'PRESENT' },
            checkInTime: { type: 'string', format: 'date-time', nullable: true, example: '2026-05-22T09:00:00Z' },
            checkOutTime: { type: 'string', format: 'date-time', nullable: true, example: '2026-05-22T18:00:00Z' },
            overtimeHours: { type: 'number', nullable: true, example: 2.5 },
            remarks: { type: 'string', nullable: true, example: 'Late due to traffic' },
            recordedBy: { type: 'integer', nullable: true, example: 1 },
            storeId: { type: 'integer', nullable: true, example: 1 },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        CreateStaffAttendanceRequest: {
          type: 'object',
          required: ['staffId', 'date'],
          properties: {
            staffId: { type: 'integer', example: 5 },
            date: { type: 'string', format: 'date-time', example: '2026-05-22T00:00:00Z' },
            status: { type: 'string', enum: ['PRESENT', 'ABSENT', 'LATE', 'LEAVE', 'HALF_DAY'], example: 'PRESENT' },
            checkInTime: { type: 'string', format: 'date-time', nullable: true, example: '2026-05-22T09:00:00Z' },
            checkOutTime: { type: 'string', format: 'date-time', nullable: true, example: '2026-05-22T18:00:00Z' },
            overtimeHours: { type: 'number', nullable: true, example: 2.5 },
            remarks: { type: 'string', nullable: true, example: 'Late due to traffic' },
            recordedBy: { type: 'integer', nullable: true, example: 1 },
            storeId: { type: 'integer', nullable: true, example: 1 },
          },
        },
        UpdateStaffAttendanceRequest: {
          type: 'object',
          properties: {
            status: { type: 'string', enum: ['PRESENT', 'ABSENT', 'LATE', 'LEAVE', 'HALF_DAY'], example: 'PRESENT' },
            checkInTime: { type: 'string', format: 'date-time', nullable: true, example: '2026-05-22T09:00:00Z' },
            checkOutTime: { type: 'string', format: 'date-time', nullable: true, example: '2026-05-22T18:00:00Z' },
            overtimeHours: { type: 'number', nullable: true, example: 2.5 },
            remarks: { type: 'string', nullable: true, example: 'Late due to traffic' },
            recordedBy: { type: 'integer', nullable: true, example: 1 },
            storeId: { type: 'integer', nullable: true, example: 1 },
          },
        },
        // ========== ORDER & PAYMENT ==========
        Order: {
          type: 'object',
          properties: {
            id: { type: 'integer', example: 1 },
            orderNumber: { type: 'string', example: 'ORD-2026-001' },
            customerId: { type: 'integer', example: 10 },
            orderDate: { type: 'string', format: 'date-time' },
            totalAmount: { type: 'number', example: 5000.00 },
            discount: { type: 'number', example: 500.00 },
            tax: { type: 'number', example: 450.00 },
            shippingCost: { type: 'number', example: 100.00 },
            grandTotal: { type: 'number', example: 5050.00 },
            status: { type: 'string', enum: ['PENDING', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED'], example: 'PENDING' },
            notes: { type: 'string', nullable: true, example: 'Please deliver after 5 PM' },
            storeId: { type: 'integer', nullable: true, example: 1 },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        CreateOrderRequest: {
          type: 'object',
          required: ['orderNumber', 'customerId'],
          properties: {
            orderNumber: { type: 'string', example: 'ORD-2026-001' },
            customerId: { type: 'integer', example: 10 },
            orderDate: { type: 'string', format: 'date-time' },
            totalAmount: { type: 'number', example: 5000.00 },
            discount: { type: 'number', example: 500.00 },
            tax: { type: 'number', example: 450.00 },
            shippingCost: { type: 'number', example: 100.00 },
            grandTotal: { type: 'number', example: 5050.00 },
            status: { type: 'string', enum: ['PENDING', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED'], example: 'PENDING' },
            notes: { type: 'string', nullable: true, example: 'Please deliver after 5 PM' },
            storeId: { type: 'integer', nullable: true, example: 1 },
          },
        },
        UpdateOrderRequest: {
          type: 'object',
          properties: {
            totalAmount: { type: 'number', example: 5000.00 },
            discount: { type: 'number', example: 500.00 },
            tax: { type: 'number', example: 450.00 },
            shippingCost: { type: 'number', example: 100.00 },
            grandTotal: { type: 'number', example: 5050.00 },
            status: { type: 'string', enum: ['PENDING', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED'], example: 'PENDING' },
            notes: { type: 'string', nullable: true, example: 'Please deliver after 5 PM' },
            storeId: { type: 'integer', nullable: true, example: 1 },
          },
        },
        OrderItem: {
          type: 'object',
          properties: {
            id: { type: 'integer', example: 1 },
            orderId: { type: 'integer', example: 1 },
            productId: { type: 'integer', example: 5 },
            variantId: { type: 'integer', nullable: true, example: 2 },
            quantity: { type: 'integer', example: 3 },
            unitPrice: { type: 'number', example: 999.99 },
            totalPrice: { type: 'number', example: 2999.97 },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
        CreateOrderItemRequest: {
          type: 'object',
          required: ['orderId', 'productId', 'quantity', 'unitPrice', 'totalPrice'],
          properties: {
            orderId: { type: 'integer', example: 1 },
            productId: { type: 'integer', example: 5 },
            variantId: { type: 'integer', nullable: true, example: 2 },
            quantity: { type: 'integer', example: 3 },
            unitPrice: { type: 'number', example: 999.99 },
            totalPrice: { type: 'number', example: 2999.97 },
          },
        },
        UpdateOrderItemRequest: {
          type: 'object',
          properties: {
            variantId: { type: 'integer', nullable: true, example: 2 },
            quantity: { type: 'integer', example: 3 },
            unitPrice: { type: 'number', example: 999.99 },
            totalPrice: { type: 'number', example: 2999.97 },
          },
        },
        Payment: {
          type: 'object',
          properties: {
            id: { type: 'integer', example: 1 },
            orderId: { type: 'integer', example: 1 },
            amount: { type: 'number', example: 5050.00 },
            method: { type: 'string', enum: ['CASH', 'CARD', 'UPI', 'BANK_TRANSFER', 'ONLINE'], example: 'UPI' },
            status: { type: 'string', enum: ['PENDING', 'PARTIAL', 'PAID', 'OVERDUE', 'CANCELLED'], example: 'PAID' },
            transactionId: { type: 'string', nullable: true, example: 'TXN-2026-12345' },
            paymentDate: { type: 'string', format: 'date-time' },
            remarks: { type: 'string', nullable: true, example: 'Payment via UPI' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        CreatePaymentRequest: {
          type: 'object',
          required: ['orderId', 'amount', 'method'],
          properties: {
            orderId: { type: 'integer', example: 1 },
            amount: { type: 'number', example: 5050.00 },
            method: { type: 'string', enum: ['CASH', 'CARD', 'UPI', 'BANK_TRANSFER', 'ONLINE'], example: 'UPI' },
            status: { type: 'string', enum: ['PENDING', 'PARTIAL', 'PAID', 'OVERDUE', 'CANCELLED'], example: 'PAID' },
            transactionId: { type: 'string', nullable: true, example: 'TXN-2026-12345' },
            paymentDate: { type: 'string', format: 'date-time' },
            remarks: { type: 'string', nullable: true, example: 'Payment via UPI' },
          },
        },
        UpdatePaymentRequest: {
          type: 'object',
          properties: {
            amount: { type: 'number', example: 5050.00 },
            method: { type: 'string', enum: ['CASH', 'CARD', 'UPI', 'BANK_TRANSFER', 'ONLINE'], example: 'UPI' },
            status: { type: 'string', enum: ['PENDING', 'PARTIAL', 'PAID', 'OVERDUE', 'CANCELLED'], example: 'PAID' },
            transactionId: { type: 'string', nullable: true, example: 'TXN-2026-12345' },
            paymentDate: { type: 'string', format: 'date-time' },
            remarks: { type: 'string', nullable: true, example: 'Payment via UPI' },
          },
        },
        // ========== STAFF SALARY ==========
        StaffSalary: {
          type: 'object',
          properties: {
            id: { type: 'integer', example: 1 },
            staffId: { type: 'integer', example: 5 },
            month: { type: 'integer', example: 5 },
            year: { type: 'integer', example: 2026 },
            baseSalary: { type: 'number', example: 50000.00 },
            attendanceBonus: { type: 'number', nullable: true, example: 5000.00 },
            deductions: { type: 'number', nullable: true, example: 2000.00 },
            advanceDeduction: { type: 'number', nullable: true, example: 3000.00 },
            netPayable: { type: 'number', example: 50000.00 },
            paidAmount: { type: 'number', example: 50000.00 },
            status: { type: 'string', enum: ['PENDING', 'PARTIAL', 'PAID', 'OVERDUE', 'CANCELLED'], example: 'PAID' },
            paymentDate: { type: 'string', format: 'date-time', nullable: true },
            remarks: { type: 'string', nullable: true, example: 'Salary for May 2026' },
            processedBy: { type: 'integer', nullable: true, example: 1 },
            storeId: { type: 'integer', nullable: true, example: 1 },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        CreateStaffSalaryRequest: {
          type: 'object',
          required: ['staffId', 'month', 'year', 'baseSalary', 'netPayable'],
          properties: {
            staffId: { type: 'integer', example: 5 },
            month: { type: 'integer', example: 5 },
            year: { type: 'integer', example: 2026 },
            baseSalary: { type: 'number', example: 50000.00 },
            attendanceBonus: { type: 'number', nullable: true, example: 5000.00 },
            deductions: { type: 'number', nullable: true, example: 2000.00 },
            advanceDeduction: { type: 'number', nullable: true, example: 3000.00 },
            netPayable: { type: 'number', example: 50000.00 },
            paidAmount: { type: 'number', example: 0 },
            status: { type: 'string', enum: ['PENDING', 'PARTIAL', 'PAID', 'OVERDUE', 'CANCELLED'], example: 'PENDING' },
            paymentDate: { type: 'string', format: 'date-time', nullable: true },
            remarks: { type: 'string', nullable: true, example: 'Salary for May 2026' },
            processedBy: { type: 'integer', nullable: true, example: 1 },
            storeId: { type: 'integer', nullable: true, example: 1 },
          },
        },
        UpdateStaffSalaryRequest: {
          type: 'object',
          properties: {
            attendanceBonus: { type: 'number', nullable: true, example: 5000.00 },
            deductions: { type: 'number', nullable: true, example: 2000.00 },
            advanceDeduction: { type: 'number', nullable: true, example: 3000.00 },
            netPayable: { type: 'number', example: 50000.00 },
            paidAmount: { type: 'number', example: 50000.00 },
            status: { type: 'string', enum: ['PENDING', 'PARTIAL', 'PAID', 'OVERDUE', 'CANCELLED'], example: 'PAID' },
            paymentDate: { type: 'string', format: 'date-time', nullable: true },
            remarks: { type: 'string', nullable: true, example: 'Salary for May 2026' },
            processedBy: { type: 'integer', nullable: true, example: 1 },
            storeId: { type: 'integer', nullable: true, example: 1 },
          },
        },
        // ========== STAFF ==========
        Staff: {
          type: 'object',
          properties: {
            id: { type: 'integer', example: 1 },
            userId: { type: 'integer', example: 10 },
            storeId: { type: 'integer', example: 1 },
            position: { type: 'string', nullable: true, example: 'Store Manager' },
            department: { type: 'string', nullable: true, example: 'Operations' },
            hireDate: { type: 'string', format: 'date-time', example: '2025-01-15T00:00:00Z' },
            salary: { type: 'number', nullable: true, example: 50000.00 },
            isActive: { type: 'boolean', example: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        CreateStaffRequest: {
          type: 'object',
          required: ['userId', 'storeId'],
          properties: {
            userId: { type: 'integer', example: 10 },
            storeId: { type: 'integer', example: 1 },
            position: { type: 'string', nullable: true, example: 'Store Manager' },
            department: { type: 'string', nullable: true, example: 'Operations' },
            hireDate: { type: 'string', format: 'date-time', example: '2025-01-15T00:00:00Z' },
            salary: { type: 'number', nullable: true, example: 50000.00 },
            isActive: { type: 'boolean', example: true },
          },
        },
        UpdateStaffRequest: {
          type: 'object',
          properties: {
            storeId: { type: 'integer', example: 1 },
            position: { type: 'string', nullable: true, example: 'Store Manager' },
            department: { type: 'string', nullable: true, example: 'Operations' },
            hireDate: { type: 'string', format: 'date-time', example: '2025-01-15T00:00:00Z' },
            salary: { type: 'number', nullable: true, example: 50000.00 },
            isActive: { type: 'boolean', example: true },
          },
        },
      },
    },
    security: [
      {
        bearerAuth: [],
      },
    ],
  },
  apis: [
    './src/routes/*.ts',
    './src/routes/*.js',
    './dist/routes/*.js',
    './api/*.ts', // if vercel uses api folder
  ],
};
